#!/bin/sh
make clean & make mrproper
#rm arch/arm/boot/dts/*/*.dtb
rm arch/arm/boot/zImage-dtb
#rm -rf magisk_module/system
rm -f repack_zip/emp/zImage
#rm -f repack_zip/emp/*.dtb
#rm -f .wireguard-fetch-lock
#rm -f drivers/platform/msm/ipa/ipa_common
echo "done"
